import type { Metadata } from "next";
import "./globals.css";
import { Oswald } from "next/font/google";
import ResponsiveNav from "./Home/Nav/ResponsiveNav";


const oswald=Oswald({
  weight :['200','300','400','500','600','700'],
  subsets:['latin']
  });


export const metadata: Metadata = {
  title: "Pavithra | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oswald.className} bg-[#212428]`}
      ><ResponsiveNav/>
        {children}
      </body>
    </html>
  );
}
